name: ðŸš€ Deploy website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸš€ Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp-pmarut.super-host.pl
          username: open_dev.pmarut
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: web/
          exclude: '
          - **/.git*/**
          - **/node_modules/**
          - **/scss/**
          - css/styles.css
          - js/scripts.js
          '
